version: '3.8'
services:
  网关_nginx:
    image: nginx:stable
    container_name: scms-nginx
    volumes:
      - ./网关_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./网关_nginx/conf.d:/etc/nginx/conf.d:ro
      - ./网页前端_webmail:/var/www/html
      - ./data/certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - 邮件服务器_postfix
      - 邮箱服务_dovecot
      - 管理后台_admin

  邮件服务器_postfix:
    build: ./邮件服务器_postfix
    container_name: scms-postfix
    volumes:
      - ./邮件服务器_postfix/main.cf:/etc/postfix/main.cf:ro
      - ./data/mail:/var/mail
      - ./data/dkim:/etc/opendkim/keys
    environment:
      - HOSTNAME=${MAIL_HOST}
    ports:
      - "25:25"
      - "587:587"
    depends_on:
      - DKIM服务_opendkim

  邮箱服务_dovecot:
    build: ./邮箱服务_dovecot
    container_name: scms-dovecot
    volumes:
      - ./邮箱服务_dovecot/dovecot.conf:/etc/dovecot/dovecot.conf:ro
      - ./data/mail:/var/mail
      - ./管理后台_admin:/opt/admin:ro
    ports:
      - "143:143"
      - "993:993"

  DKIM服务_opendkim:
    build: ./DKIM服务_opendkim
    container_name: scms-opendkim
    volumes:
      - ./DKIM服务_opendkim/opendkim.conf:/etc/opendkim.conf:ro
      - ./data/dkim:/etc/opendkim/keys
    ports:
      - "8891:8891"

  管理后台_admin:
    build: ./管理后台_admin
    container_name: scms-admin
    volumes:
      - ./data/mail:/var/mail
      - ./data/dkim:/data/dkim
      - ./管理后台_admin:/opt/admin
    environment:
      - FLASK_ENV=production
      - ADMIN_SECRET=${ADMIN_SECRET}
    ports:
      - "8000:8000"

volumes:
  maildata:
  dkim: